name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install
      run: make install
    - name: lint
      run: make lint
    - name: build
      run: make build
      env:
        CC_TEST_REPORTER_ID: 168ee6fa1d39c13d104674a13d5e227eec291bd1a40ad0c5b2c08f34b630401f

