name: Node CI

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build, and test
        run: |
          make install
          make build
          make test
        env:
          CI: true
      - name: Run linter
        run: |
          make lint
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.4.0
        env:
          CC_TEST_REPORTER_ID: 168ee6fa1d39c13d104674a13d5e227eec291bd1a40ad0c5b2c08f34b630401f
        with:
          coverageCommand: make test-coverage
          debug: true
